<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>onionsat_logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="onionsat_logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AltoHttp" Version="1.5.2" />
    <PackageReference Include="GMap.NET.Core" Version="2.1.7" />
    <PackageReference Include="GMap.NET.WinForms" Version="2.1.7" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="OxyPlot.WindowsForms" Version="2.1.2" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.9.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>